version: "3.9"

services:
  credit-api:
    build:
      context: .
      dockerfile: services/credit-api/Dockerfile
    container_name: credit-api
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./ml-credit/models:/app/ml-credit/models:ro
      - ./ml-credit/artifacts:/app/ml-credit/artifacts:ro
    restart: unless-stopped
    networks:
      - risk-net
  letter-api:
    build:
      context: .
      dockerfile: services/letter-api/Dockerfile
    container_name: letter-api
    ports:
      - "8001:8001"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./ml-letter/models:/app/ml-letter/models:ro
      - ./data:/app/data:ro
    restart: unless-stopped
    networks:
      - risk-net
  
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: risk-backend
    env_file:
      - ./infra/.env
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/risk-intelligence
      - ML_CREDIT_URL=http://credit-api:8000/score
      - ML_LETTER_URL=http://letter-api:8001/letter
    depends_on:
      - mongo
      - credit-api
      - letter-api
    ports:
      - "5000:5000"
    networks:
      - risk-net
  
  mongo:
    image: mongo:6
    container_name: risk-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - risk-net

volumes:
  mongo-data:

networks:
  risk-net:
    driver: bridge
